#!/bin/bash
php app/console cache:clear --env=test
php app/console doctrine:mongodb:schema:drop --env=test
php app/console doctrine:mongodb:fixtures:load --append --fixtures=tests/DataHub --env=test
bin/phpunit -c app --stop-on-failure --coverage-html scripts/coverage
