#!/bin/bash

if [ -z "$1" ]
  then
    echo "Usage: please supply the URL of the Datahub instance you want to test as an argument"
    exit 0
fi

BASE_URL=$1

LIDOFILE=`dirname $0`/../src/DataHub/ResourceAPIBundle/Tests/Resources/LidoXML/LIDO-Example_FMobj00154983-LaPrimavera.xml

TOKEN=`curl -s "$BASE_URL/oauth/v2/token?grant_type=password&username=admin&password=datahub&client_id=slightlylesssecretpublicid&client_secret=supersecretsecretphrase" | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["access_token"]'`

echo "Token=$TOKEN"

echo ""
echo ""
echo "List data:"
curl -s -H "Authorization: Bearer $TOKEN" -X "GET" "$BASE_URL/api/v1/data.json" | head -c 500

echo ""
echo ""
echo "POST data:"
curl -s -i -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/lido+xml" -X "POST" --data @$LIDOFILE "$BASE_URL/api/v1/data?foo=bar" | head -c 500

echo ""
echo ""
echo "GET all data:"
curl -s -i -H "Authorization: Bearer $TOKEN" -X "GET" "$BASE_URL/api/v1/data" | head -c 500

echo ""
echo ""
echo "GET single data:"
curl -s -i -H "Authorization: Bearer $TOKEN" -X "GET" "$BASE_URL/api/v1/data/DE-Mb112%2Flido-obj00154983" | head -c 500

echo ""
echo ""
echo "PUT single data:"
LIDOFILE2=`dirname $0`/../src/DataHub/ResourceAPIBundle/Tests/Resources/LidoXML/LIDO-Example_FMobj00154983-LaPrimavera-updated.xml
curl -s -i -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/lido+xml" -X "PUT" --data @$LIDOFILE2 "$BASE_URL/api/v1/data/DE-Mb112%2Flido-obj00154983" | head -c 500

echo ""
echo ""
echo "GET single updated data:"
curl -s -i -H "Authorization: Bearer $TOKEN" -X "GET" "$BASE_URL/api/v1/data/DE-Mb112%2Flido-obj00154983" | head -c 500


echo ""
echo ""
echo "DELETE data:"
curl -s -i -H "Authorization: Bearer $TOKEN" -X "DELETE" "$BASE_URL/api/v1/data/DE-Mb112%2Flido-obj00154983" | head -c 500

echo ""
echo ""
echo "GET no data:"
curl -s -i -H "Authorization: Bearer $TOKEN" -X "GET" "$BASE_URL/api/v1/data/DE-Mb112%2Flido-obj00154983" | head -c 500

echo ""
echo ""
