<?php

namespace DataHub\UserBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{

    /**
     * Return all stored users.
     *
     * @return int
     */
    public function getAll()
    {
        return
            $this->createQueryBuilder('User')
                ->getQuery()
                ->execute();
    }

    /**
     * Return users with a matching confirmation token.
     * 
     * @return User $user
     */
    public function findByConfirmationToken($token)
    {
        return
            $this->createQueryBuilder('user')
                ->field('confirmationToken')->equals($token)
                ->getQuery()
                ->getSingleResult();
    }

    public function getAdmin()
    {
        return
            $this->createQueryBuilder('user')
                ->field('roles')->equals('ROLE_ADMIN')
                ->getQuery()
                ->getSingleResult();
    }

    /**
     * Return the number of stored users.
     *
     * @return int
     */
    public function count()
    {
        return
            $this->createQueryBuilder('User')
                ->count()
                ->getQuery()
                ->execute();
    }
}
