<?php

namespace DataHub\UserBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{

    /**
     * Return all stored users.
     *
     * @return int
     */
    public function getAll()
    {
        return
            $this->createQueryBuilder('Record')
                ->getQuery()
                ->execute();
    }

    /**
     * Return the number of stored users.
     *
     * @return int
     */
    public function count()
    {
        return
            $this->createQueryBuilder('User')
                ->count()
                ->getQuery()
                ->execute();
    }
}
