<?php

namespace DataHub\OAuthBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends DocumentRepository
{
}
